/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DuesRouteImport } from './routes/dues'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as WastageRouteImport } from './routes/wastage'
import { Route as PartyIdRouteImport } from './routes/party.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuesRoute = DuesRouteImport.update({
  id: '/dues',
  path: '/dues',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const WastageRoute = WastageRouteImport.update({
  id: '/wastage',
  path: '/wastage',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyIdRoute = PartyIdRouteImport.update({
  id: '/party/$id',
  path: '/party/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dues': typeof DuesRoute
  '/expenses': typeof ExpensesRoute
  '/parties': typeof PartiesRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/wastage': typeof WastageRoute
  '/party/$id': typeof PartyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dues': typeof DuesRoute
  '/expenses': typeof ExpensesRoute
  '/parties': typeof PartiesRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/wastage': typeof WastageRoute
  '/party/$id': typeof PartyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dues': typeof DuesRoute
  '/expenses': typeof ExpensesRoute
  '/parties': typeof PartiesRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/wastage': typeof WastageRoute
  '/party/$id': typeof PartyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dues'
    | '/expenses'
    | '/parties'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/wastage'
    | '/party/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dues'
    | '/expenses'
    | '/parties'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/wastage'
    | '/party/$id'
  id:
    | '__root__'
    | '/'
    | '/dues'
    | '/expenses'
    | '/parties'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/wastage'
    | '/party/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuesRoute: typeof DuesRoute
  ExpensesRoute: typeof ExpensesRoute
  PartiesRoute: typeof PartiesRoute
  ProductsRoute: typeof ProductsRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  WastageRoute: typeof WastageRoute
  PartyIdRoute: typeof PartyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dues': {
      id: '/dues'
      path: '/dues'
      fullPath: '/dues'
      preLoaderRoute: typeof DuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wastage': {
      id: '/wastage'
      path: '/wastage'
      fullPath: '/wastage'
      preLoaderRoute: typeof WastageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$id': {
      id: '/party/$id'
      path: '/party/$id'
      fullPath: '/party/$id'
      preLoaderRoute: typeof PartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuesRoute: DuesRoute,
  ExpensesRoute: ExpensesRoute,
  PartiesRoute: PartiesRoute,
  ProductsRoute: ProductsRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  WastageRoute: WastageRoute,
  PartyIdRoute: PartyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
